import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";
import { VscTrash, VscEdit } from "react-icons/vsc";
import { api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime);

const PostView = () => {
  const { data, isLoading } = api.post.getAllPosts.useQuery();
  if (!data) return null;
  if (isLoading) return <div>Loading...</div>;

  return (
    <>
      {data.map(({ author, post }) => (
        <div key={post.id} className="flex w-full justify-center">
          <div className="h-auto w-full rounded-l-md bg-white p-3">
            <div className="max-w-xs pl-2">
              <div className="flex items-center gap-2 pb-2">
                <h3 className="text-md max-w-[190px] overflow-hidden font-semibold text-slate-600">
                  @{author.name}
                </h3>
                <label className="text-xs text-slate-400">
                  · {dayjs(post.createdAt).fromNow()}
                </label>
              </div>
              <p>{post.content}</p>
            </div>
          </div>
          <div className="flex w-10 flex-col items-end justify-start gap-3 rounded-r-md bg-white">
            <button className="flex h-6 w-6 items-center justify-center rounded-l-full rounded-r-md bg-gradient-to-br from-[#0055f3] to-[#00c0fa] pl-1 duration-200 ease-in-out hover:w-10">
              <VscEdit />
            </button>
            <button className="flex h-6 w-6 items-center justify-center rounded-l-full rounded-r-md bg-gradient-to-br from-[#ff042d] to-[#ff4b63] pl-1 duration-200 ease-in-out hover:w-10">
              <VscTrash />
            </button>
          </div>
        </div>
      ))}
    </>
  );
};

const Home: NextPage = () => {
  const [inputNews, setInputNews] = useState("");
  const { data: sessionData } = useSession();
  const ctx = api.useContext();

  const { mutate, isLoading } = api.post.createNewPost.useMutation({
    onSuccess: () => {
      setInputNews("");
      void ctx.post.getAllPosts.invalidate();
    },
  });

  return (
    <>
      <Head>
        <title>News Page 👀</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-wrap items-start justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] ">
        <div>
          <div className="m-5 flex items-start justify-center">
            <AuthShowcase />
          </div>
          <div className="flex w-full flex-col items-start justify-center gap-10">
            {sessionData && (
              <div className="flex w-full flex-wrap gap-1">
                <label className="w-full text-white">Enter news:</label>
                <div className="flex w-full max-w-md flex-col">
                  <input
                    type="text"
                    placeholder="..."
                    value={inputNews}
                    onChange={(e) => {
                      setInputNews(e.target.value);
                    }}
                    className="rounded-md p-1 pl-2 focus:outline-none"
                  />
                  <div className="flex justify-end">
                    <button
                      type="submit"
                      className=" rounded-md bg-gradient-to-r from-[#6700f7] to-[#9248f3] p-1 px-6 font-semibold text-white duration-200 active:scale-110"
                      onClick={() => {
                        mutate({ content: inputNews });
                      }}
                    >
                      Submit
                    </button>
                  </div>
                </div>
              </div>
            )}
            <PostView />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data } = useSession();
  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-xl text-white">
        {data && <span>Logged in as {data.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={data ? () => void signOut() : () => void signIn()}
      >
        {data ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
